// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU2y5VKvKlDbbgOsvnQcdjnLLBkw2Ya58',
    appId: '1:425134419399:web:90b3b0cf65adb358e3bde2',
    messagingSenderId: '425134419399',
    projectId: 'healty-meal-4591f',
    authDomain: 'healty-meal-4591f.firebaseapp.com',
    storageBucket: 'healty-meal-4591f.appspot.com',
    measurementId: 'G-DMRVH99H91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNytWn-X6Pz7wCqsgvgsiu56f7297mYEg',
    appId: '1:425134419399:android:e83f94711172919fe3bde2',
    messagingSenderId: '425134419399',
    projectId: 'healty-meal-4591f',
    storageBucket: 'healty-meal-4591f.appspot.com',
  );
}
